name: Deploy GitHub Pages with Concealed Name

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholder with concealed name
        run: sed -i 's/__NAME__/${{ vars.CONCEALED_NAME }}/g' index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # This is the branch that GitHub Pages serves
          folder: .  # Deploy the root folder (adjust if needed)
