name: Deploy GitHub Pages with Concealed Name

on:
  workflow_dispatch:
    inputs:
      CONCEALED_NAME:
        description: 'The concealed name to replace'
        required: true
        default: 'DefaultName'  # Optional default value

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # Ensure correct branch

      - name: Debug file structure
        run: ls -R  # List files to confirm index.html exists

      - name: Debug concealed name
        run: echo "Concealed Name: ${{ github.event.inputs.CONCEALED_NAME }}"  # Accessing input value

      - name: Replace placeholder with concealed name
        run: |
          echo "Replacing __NAME__ with ${{ github.event.inputs.CONCEALED_NAME }}"
          sed -i "s/__NAME__/${{ github.event.inputs.CONCEALED_NAME }}/g" index.html  # Double quotes to ensure variable expansion works
        working-directory: .  # Adjust path if needed

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .  # Adjust if using a subfolder
