name: Deploy GitHub Pages with Concealed Name

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create dist directory
        run: mkdir -p dist

      - name: Copy files to dist (excluding .git and dist itself)
        run: |
          find . -maxdepth 1 -not -name dist -not -name .git -print0 | xargs -0 -I {} cp -r {} dist/

      - name: Replace placeholder in index.html and inject JS variable
        run: |
          echo "Before replacement:"
          cat dist/index.html  # Show the contents of index.html before
          sed -i "s/__NAME__/Loading.../g" dist/index.html # Optional default text
          echo "After replacement:"
          cat dist/index.html  # Show the contents of index.html after
          echo "Injecting JavaScript variable..."
          echo "window.nameFromEnv = '${{ secrets.CONCEALED_NAME }}';" >> dist/script.js
          echo "Contents of script.js:"
          cat dist/script.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages