name: Deploy GitHub Pages with Concealed Name

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Replace placeholder with concealed name
        run: sed -i "s/__NAME__/${{ secrets.CONCEALED_NAME }}/g" index.html
        shell: bash

      - name: Deploy to GitHub Pages (using a temporary branch)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Deploy the current directory (with the modified index.html)
          branch: gh-pages
          clean: true # Important: Clean the gh-pages branch first