name: Deploy GitHub Pages with Concealed Name

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create dist directory
        run: mkdir -p dist

      - name: Copy files to dist (excluding dist itself)
        run: |
          cp -r index.html dist/  # Copy index.html
          cp -r script.js dist/   # Copy script.js
          # Add other files as needed (e.g., cp -r style.css dist/)

      - name: Replace placeholder in index.html and inject JS variable
        run: |
          sed -i "s/__NAME__/Loading.../g" dist/index.html # Optional default text
          echo "window.nameFromEnv = '${{ secrets.CONCEALED_NAME }}';" >> dist/script.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages