name: Deploy GitHub Pages with Concealed Name

on:
  push:
    branches:
      - main  # Ensure it's the correct branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CONCEALED_NAME: "YourConcealedName"  # Directly define your variable here for debugging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # Ensure correct branch

      - name: Debug environment variables
        run: |
          echo "Listing environment variables:"
          printenv  # List all environment variables to see if CONCEALED_NAME is available

      - name: Debug concealed name
        run: |
          echo "Concealed Name (should be 'YourConcealedName'): $CONCEALED_NAME"  # Should print the value of the variable

      - name: Replace placeholder with concealed name
        run: |
          echo "Replacing __NAME__ with $CONCEALED_NAME"
          sed -i "s/__NAME__/$CONCEALED_NAME/g" index.html  # Double quotes to ensure variable expansion works
        working-directory: .  # Adjust path if needed

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .  # Adjust if using a subfolder
