name: Deploy GitHub Pages with Concealed Name

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Build the site (if applicable)
        run: npm run build # or hugo, jekyll, etc.

      - name: Replace placeholder in index.html (using environment variable)
        run: |
          sed -i "s/__NAME__/Loading.../g" ./dist/index.html # Replace with default text
          echo "window.nameFromEnv = '${{ secrets.CONCEALED_NAME }}';" >> ./dist/script.js # Create JS variable
        shell: bash

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          branch: gh-pages