name: Deploy GitHub Pages with Concealed Name

on:
  push:
    branches:
      - main  # Ensure correct branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # Ensure correct branch

      - name: Debug file structure
        run: ls -R  # List files to confirm index.html exists

      - name: Replace placeholder with concealed name
        run: |
            echo "Before replacement:"
            cat index.html  # Show the file before the change
            echo "Replacing __NAME__ with '${{ secrets.CONCEALED_NAME }}'"
            sed -i "s/__NAME__/${{ secrets.CONCEALED_NAME }}/g" index.html
            echo "After replacement:"
            cat index.html  # Show the file after the change
        shell: bash

      - name: Commit changes (GitHub Actions bot)
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add index.html
            git commit -m "Automated update" || echo "No changes to commit"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # Adjust if using a subfolder
