name: Deploy GitHub Pages with Concealed Name

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create dist directory
        run: mkdir -p dist

      - name: Copy files to dist
        run: |
          cp index.html dist/
          cp script.js dist/

      - name: Replace encoded name in script.js  # <--- Corrected
        run: |
          export CONCEALED_NAME="${{ secrets.CONCEALED_NAME }}"
          ENCODED_NAME=$(echo "$CONCEALED_NAME" | base64) # Encode the name
          sed -i "s/\\*\\*\\*ENCODED_NAME\\*\\*\\*/$ENCODED_NAME/g" dist/script.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages